### ISSUE TITLE
org.eclipse.jetty.servlet.ServletHolder class shipped by RemoteSwingLibrary clashes with the class from Jetty if it is present in the classpath

### ISSUE THREAD

**Issue by karusha** [robotframework/remoteswinglibrary#96] opened 2020-11-16 16:51 UTC
After update one of our jars (OpenAdaptor), we have proper copy of Jetty,which clashes with what RemoteSwingLibrary has. As a result we are getting below errors:

they start Kristall but then do not see it started, see the following errors in logs:

16:36:46.169	Process is running, but application startup failed	
16:36:46.202	FAIL	RemoteSwingLibraryTimeoutError: Agent port not received before timeout
and then in stdout:
2020-11-16 16:32:03,110 ERROR AWT-EventQueue-0 [UncaughtExceptionHandler]{null} - Uncaught Exception occurred in thread "AWT-EventQueue-0"
java.lang.NoSuchMethodError: org.eclipse.jetty.servlet.ServletHolder.<init>(Lorg/robotframework/remoteswinglibrary/javax/servlet/Servlet;)V
	at org.robotframework.remoteserver.RemoteServer.<init>(RemoteServer.java:75)
	at org.robotframework.remoteserver.RemoteServer.<init>(RemoteServer.java:65)

Would it be possible to fix it?

**Comment by mihaiparvu** [comment] 2021-03-10 12:36
Closing as it seems to be a duplicate of #94

**Closed by mihaiparvu** 2021-03-10 12:36 UTC
