### ISSUE TITLE
Issue in importing RemoteSwingLibrary to RobotFramework 

### ISSUE THREAD

**Issue by sandhyk** [robotframework/remoteswinglibrary#26] opened 2015-09-01 06:20 UTC
Hi,

I have downloaded the remoteswinglibrary-2.0.3.jar and also included it in PATH under system variables. On trying to import the library to RobotFramework, it says import failed with the below logs,

20150901 11:37:20.625 [INFO]: Started RIDE 1.4.1 using python version 2.7.10 with wx version 2.8.12.1 in win32.

20150901 11:37:24.234 [WARN]: Importing test library "RemoteSwingLibrary" failed

Traceback (most recent call last):
Importing test library 'RemoteSwingLibrary' failed: ImportError: No module named RemoteSwingLibrary
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Python27\lib\site-packages\robotide\lib
  C:\Python27\lib\site-packages\wx-2.8-msw-unicode
  C:\Python27\lib\site-packages\wx-2.8-msw-unicode
  C:\Python27\Scripts
  C:\Python27\lib\site-packages\pywinauto-0.5.1-py2.7.egg
  C:\WINDOWS\system32\python27.zip
  C:\Python27\DLLs
  C:\Python27\lib
  C:\Python27\lib\plat-win
  C:\Python27\lib\lib-tk
  C:\Python27
  C:\Python27\lib\site-packages
  C:\Python27\lib\site-packages\win32
  C:\Python27\lib\site-packages\win32\lib
  C:\Python27\lib\site-packages\Pythonwin
  C:\Python27\lib\site-packages\robotide\spec
  .
  C:\Python27\lib\site-packages\robotide\spec\remote
  File "C:\Python27\lib\site-packages\robotide\spec\librarymanager.py", line 81, in _fetch_keywords
    return get_import_result(path, library_args)
  File "C:\Python27\lib\site-packages\robotide\spec\libraryfetcher.py", line 20, in get_import_result
    lib = robotapi.TestLibrary(path, args)
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 41, in TestLibrary
    libcode = importer.import_class_or_module(name)
  File "C:\Python27\lib\site-packages\robotide\lib\robot\utils\importer.py", line 64, in import_class_or_module
    self._raise_import_failed(name, err)
  File "C:\Python27\lib\site-packages\robotide\lib\robot\utils\importer.py", line 99, in _raise_import_failed
    raise DataError('\n'.join(msg))

It would be great if anyone could help me sort this out. Thanks.

**Comment by mgladki** [comment] 2015-09-01 09:12
Did you add the .jar file to the PATH or PYTHONPATH variable? It looks like it's not in the PYTHONPATH where it should be. Try adding it there and running your test again.

**Comment by sandhyk** [comment] 2015-09-01 10:00
Hi,

Thank you for the response. 

I removed it from PATH and included "C:\Python27\Scripts\remoteswinglibrary-2.0.3.jar" creating PYTHONPATH. It still says the same. Unable to import library.

**Comment by javier-jimenez** [comment] 2015-10-22 15:56
Check my answer from issue 29 https://github.com/robotframework/remoteswinglibrary/issues/29

That fixed it for me.

**Comment by pekkaklarck** [comment] 2016-01-29 10:04
This and #29 are duplicates. I already commented the latter about the root cause so I'll close this issue.

**Closed by pekkaklarck** 2016-01-29 10:04 UTC
